import Head from 'next/head';
import { useSelector, useDispatch } from 'react-redux';
import { increment } from '../redux/redux';

export default function Home() {
  const state = useSelector((state: any) => state.counterReducer);
  const dispatch = useDispatch();

  const add = () => {
    dispatch(increment());
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>redux</h1>
      <h4>{state}</h4>
      <button onClick={add}>add</button>
    </div>
  );
}
